Funcionalidad/navbar
julianf97/plataforma-streaming pull request #4
Opened 2023-06-03 14:29 UTC by julianf97

2023-06-12 21:57 UTC, DiegoNG90 commented
veo el pr vacio de cambios 👀

2023-07-05 20:04 UTC, DiegoNG90 commented on src/app/components/Navbar/Navbar.jsx
> +    </GralContainer>
Acá ésto quedó muy verboso, con muchos componentes.
Algunos veo que están mal indentados (ejemplo linea 24), mientras que otros tienen nombres un poco raros (GralContainer? BorderAll?)
No es blocker, pero acá hay oportunidad de mejora/refactor en ésta u otra iteracion.

2023-07-05 20:05 UTC, DiegoNG90 commented on src/app/components/Square/Square.jsx
> +const Square = (props) => (
Vi que antes usaste el nombre IconUser.
Aplicaría el mismo concepto acá: IconSquare.

O quizás, en inglés, mejor quedaría UserIcon y SquareIcon.

2023-07-05 20:05 UTC, DiegoNG90 commented on src/app/components/TV/TV.jsx
> +const TV = (props) => (
TVIcon ?

2023-07-07 15:23 UTC, DiegoNG90 commented on src/app/components/Navbar/Navbar.jsx
> +            <IconUser/>
Te copas y le cambias por <UserIcon />?

2023-07-07 15:23 UTC, DiegoNG90 commented on src/app/components/IconUser/IconUser.jsx
> +const IconUser = (props) => (
Te copas y lo renombras como UserIcon?
Al archivo, a la carpeta y en el index.js tmb.

2023-07-07 16:07 UTC, julianf97 commented on src/app/components/IconUser/IconUser.jsx
> +const IconUser = (props) => (
Mas vale brost

2023-07-07 16:26 UTC, DiegoNG90 requested changes

2023-07-07 16:26 UTC, DiegoNG90 commented on src/app/components/UserIcon/UserIcon.jsx
> +export default IconUser;
Falta cambiarlo acá

2023-07-08 00:34 UTC, DiegoNG90 approved these changes

2023-07-08 00:37 UTC, merged